[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e6032eeb0cbdeffa22174f80e2bc0221fee8655"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "b90b1afd3fe4d05cc9e03ac651519c7327b1b12308cf00a95a34b51cadcca656"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.aarch64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "598657fda5797e8e76f87bb4330b4aa50d65c21a"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "fd19be6271b5cd6aa59f799d1224ca34f596bd4c2d409450c8379bb001b5411b"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.aarch64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d57ebfe5175aa051dd7b8ca693f98a67d8ef10e3"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "f54daea72db48379b75cd7486ec50a6780b8bf3621ac3715d1f5e1cb36392e00"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9a102ffa24bf2f9f0caf60149204663988e9b2d"
os = "windows"

    [[Cgl.download]]
    sha256 = "7042a0438904adfacc325545e192df153fcabde4ad5e99741525edb80cb01ec9"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8822f187f4a89f43cf6b55609b096d3d3ca78a1"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "e0a7a59900f76cb714a1a3e7b84c6bf6ab97aef9d5ab12c098c3700f3c59fb41"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.i686-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9ddf6d4c96d6db2e49948da927c8cbaa273e826"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "63c7c13093bb3afd0197fb44d77a9394a921fc6181d24cf1f4b52143e098559f"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.x86_64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a874499c42203c3ed04be6fcc63c699d381805c"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "4c3e4e499b3b90f94b621f990467b4424d7bdf3febf50a38af6286353f1938fe"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a1fadcde08d078bb85d9a33843c9e76da48ebfc"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "a5b02b47500fe59d8a1ff2e95ab049f05735d1e47e6f769ee9df1edb16195419"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.i686-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bc42835554a6bf5aeb8733e4f03e3dafa652f6c"
os = "macos"

    [[Cgl.download]]
    sha256 = "b9d99f3dff57ec6ed55dad853879b90be042296df8d6b58eaeafbeed4f3fc30e"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49624686aa7eac1e2b48e0e9c3e5d540335ba2e7"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "c7f37c1a2a2d1973b2908806d5721ae0acf1ddb74ad3222d9fd472493c2c0913"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.i686-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc0ab03f3ec6b02d4e82ed3841715f28e81bfadc"
os = "windows"

    [[Cgl.download]]
    sha256 = "04d3c0389fc80bd08e80bb47da3e7d3982f41329d57ab49be882bcafa6f583e4"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46411fc6d1977f9731c6cb7ab30ea25b1a987aec"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "98720a309cd486e923745c6b611ec4d0cd1ebcd8d3e796cf082e538245a78346"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b1dee2bf9e1694ffc7bd08e875c4c49ae7a7d6c"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "12579d64a95204b677b67f5b42cf43377490f0136d961d135a40fa94b895afb9"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eaca444e43e35b68413244cf456e28c9032a2e45"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "b52d6ccbac3d11d51a5a69d9884457eecd234be6c8911c16c166697cecba4f0c"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.x86_64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebab79f1d3b358df8c98f020f51b0bfbe15e1e2a"
os = "macos"

    [[Cgl.download]]
    sha256 = "432de760c419c5fddf80615f395d16502e0f75e44ba8c7eddfa539df60a2303a"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "705d4bd67edd8a1c46646430a704602bd57ae063"
os = "windows"

    [[Cgl.download]]
    sha256 = "77a3844e160263f2d3c75acf4988c0bec8d97bc92aa0ac8fbdc888de289cb228"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.i686-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "197bfa57684c226f5a98fdca21497fdd7bdd177c"
os = "windows"

    [[Cgl.download]]
    sha256 = "72e80c383e98f20d6a7ad352f362d07da93d5d0414ef94ad9e5d79c29af2e539"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.i686-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccae5ded730709dc020ecbdf2ac852bcc26a2e33"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "5df3bdcf394be8f7686f6d6ad55a4db8309ea6b4428fac81aa37678376f985e7"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "410da197a4c7d00a43463767db356d6dd1d1014c"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "dcbe6aa42af0b11358317c45b54dbb2cdf4f799865233ac20039487cab4eb063"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "343a28ca221b9c5d07b3d71f6271bbb3b3e6c2d1"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "22e7601dd2898e60e88a4f892504d514a569c530d7334b432bccd391b597b72c"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aeafed9cfa1ebe32dbfbf486e7106c2b7a48b8f6"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "32c8513f5107575fd5fdcd8e4e275915d44a70862346b11f6e52f17c9a8297fe"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "930efdfab91e6baca8ff72a101ade95ef30d649b"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "aef16046f117783571ee43628efe71594a13445587ba3da0c076d8c63ca12093"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+2/Cgl.v0.60.2.i686-linux-musl-cxx03.tar.gz"
