[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "474b6a9904906cb6a6d9f66bd8cb44ff3f3998a0"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "d31a460b12dd72b17f08ab8cb2f7a5fe2d6abab03fee9c2badef3fe9200fa2e3"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.i686-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b443b917ede58b41572350f7326f9540159c69da"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "f174cb988942528329f91e73bf03b2843396150689e966cab86c331a1cc069d2"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.aarch64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "192e4f79da688947821b94bbe271f1574a743633"
os = "windows"

    [[Cgl.download]]
    sha256 = "f62f0372c498a7ce6634feefefc384c049588c5066b16762173dcd08d8778b06"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.i686-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b484fab1a6f67963351c8fae1902a84c8323fc6"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "c54fd80397c974d983c3330418374c0d88a26963840ff5438b526033a8b4b50a"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70630915ff32de651c384fba38ee91a720774736"
os = "windows"

    [[Cgl.download]]
    sha256 = "83cade2441167ed5ce4b571fe212e5c68dfb1a9b10b6d555d7f4bd39e6296d01"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1d9516d874f207f73168d147f3b9f3f9bb97863"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "087b8c3fcacd7571f19d0672c53cbb59ff84e54ecd5ec4f67d60c052a0a3fae9"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cgl]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fb0050f330849012212c7f3aa7780b4305d400b"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "fe348b74be56da45ddbf70cbe169f52145f2152b78473b0f544b972e4f741f02"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0d270748d96ecdbcdcff800edf3b09111b3d59b"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "6f40133f3b55fa0c5e8754ea7d5c894e7c96fe5e5861b24a75bee04d19638207"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35b93d053bb4a2066016099315d50eeb128e7c61"
os = "windows"

    [[Cgl.download]]
    sha256 = "18829f52da8437927b7b3eb93eee61cbebf7858ef72d15c573f17778ee77d946"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0ccd748b0ae926bdbce775e34cd1d259dcfac19"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "6b04130c97b0c88de00ba0e3d5fa7a4d75a66bf76963aed8b25f6cf23410f3b7"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.x86_64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f900c9337c08a4c71d96379f73f3e791fdfa0559"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "fe27dcf3b9d6ea693b54df177420502487c8631274657d9ab200fa3b76029804"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.i686-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c46115afb4550b98d951dde63bdb39c8230672c"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "82ceb3abcd77942bf8f6bd50e01aedfb9bee83989262dc0cf861169c5a42b3ba"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.x86_64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a0c6c4c45f4dcc4cd3c33297151be4f416eb808"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "587c88de478feec426326a8c3446c2c1de952f7cfa906d915953a1b7b8f9bc64"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "794a8052c83d868a8d342ce9934a7016d356197c"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "852ac9cc02e2cff1af820b65dec8d54045aaf81d6c337d60e84a767d51a3b3d6"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.aarch64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60b50a8861224cc47fa0e2cd2c0408d154236381"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "e37dbb2af6770fa6d64c59ee47f55698fd5916102e9f2d2c034341fa85b6fcb5"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c4205b88af91241839346e941b418fa801a85e6"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "97c443422c9e690fbc70670ce9b33fd444f523dbe5096d34793e8587811b9bc3"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.i686-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "894f4b03c89037108822872fd76defbf2c30ca97"
os = "windows"

    [[Cgl.download]]
    sha256 = "d6adf60516024e35a2a7bf0a88622d899b8bd4a1b6296af5aa948ebc6e6dcb1e"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.i686-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04afba71e451d6f4ee05a9c241e799313445116e"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "c82ffcebf11e571b1964ad48f79a5ade93a2a7de6d90474b2f44ffb558a5e05f"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93b3d864f32b4cd86b108b8657af721d53d70c8b"
os = "macos"

    [[Cgl.download]]
    sha256 = "4b2370ba08ebf7e851242902e6634cdad7d78ab2a6f72a563e5c05c419a9a8ed"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14eb4cd3e67c1aa090a558115b47e44ba9776e16"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "121e30445d624a940f9ed7b0ba8fed0bb252a130c33156dd410f19f8c9c3b359"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.i686-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34a24e4c47c75455536cdd93c0c353dd95884073"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "273b038f097cf6999456388f8aef2e757e06b83f8f1e8471e158fb2544aaf79a"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a396b62753b407e1f82dc49d3b47a5ac257ff20"
os = "macos"

    [[Cgl.download]]
    sha256 = "b2cf59079bea73339b2f21d9812be818798513c3614e86dff678192f7ab9d862"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12664be9089f127bb09adfc15cf3fa28d36f28c1"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "0c6d33acef7f2a17f3b10ff5c71f2a0f5b7736465e8610ecc574ae1b23c64080"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cgl]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09ca8e479751f168311043f425251a49456b232c"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "5c62fbaa2ea618b548cbe55f70ea8ec44ffc7cd064517690f64e67c70f1220c2"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+5/Cgl.v0.60.2.powerpc64le-linux-gnu-cxx03.tar.gz"
