[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff93d6486cd77957eb72a63d082869265985c141"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "8d477fadc048bfcd70f0dcfcc9f72f7f448a87c518bad3229202a694202f5aca"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.aarch64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af556b4c50b9f320a0c17b95b5294e10ecf49e30"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "b49aa1acbafe2ae4f1a6f0673482617eaf9741d1e448dbd7165bb73e722d5690"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.aarch64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35d53ef3d94b82ff12626bf0d4cd512d9b54568d"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "5b878b52e4d9a8713419c631b6688fb2128a452143d10cf8f676fbe099a213f0"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.aarch64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bff5fc67ffff41b8ed2a128412f6659d9d17441"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "ecb3328d0869086a42bbbf21bac647d70332672ebe5f50fb194f3951eb010aea"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.aarch64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4836707030578192aae8c8eb64f323694aadde36"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "734805bc5f672ca5c883202767dc6b36aef0b0132a17c880872060bdf07699d9"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cgl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "628fa62f16760801bc454f0bdd7f04e8eb1950f0"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "07a3ef843afdfc0a4bedbed1c6fe702451ece2231d0d2a558a7ca8a2be7bfe0b"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e87e255168d246569d20956ef52958df5b5ae9f8"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "414759bf13d2750ff3ba814cac9936bdb1aa5e8a1ad7c0f4a5e628f4d8ed049a"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cgl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "307b51b1dbebc76a1bd779858d8e066985bc16ab"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "4293ab80abcf8f7eace7012295bfbd6bc6c5774add6d7d06b7b11996c280f147"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb8c5464db08b68abfbe2d9c8b15c42b33ccf014"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "99a84648b98c275e290d16e9976aef57666ea7edec7ab1f8603d88a77306464a"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.i686-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11fff95bebf2ba7cb6fcad56a8bc4b9493a4cbcc"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "49a6d2ea612b4c7beb707d04bc729d90941d87f1b7796b1823bf8c396aefa49a"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.i686-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff6f3763ad93a95a3915c52943710115ade93fa1"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "31570cce7ec9b5655059a78aa5942fab2f9ea6364ebf875279a3c094b8e61448"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.i686-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "724bc715311fa9d7749b7e79d218228427c07b71"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "b2a27954e55f6aa4fcf0815ba33c310959e09dbc87ddde99812b180db4706c8b"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.i686-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5f97c85fce67f0f12465c0f1e7a108f44cada02"
os = "windows"

    [[Cgl.download]]
    sha256 = "70c2f9813be34502b95a1416f6a10bde0a5e11fdcb28b8d06c3fd3a74dfa9de9"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.i686-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "527d36bf3f2889582b0e83c43945cc1d91fb4a0b"
os = "windows"

    [[Cgl.download]]
    sha256 = "3b820f17bf77b43420d40d9b228ceb0b1c83e00b1b51a135ce60cd79793ca17e"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.i686-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b74fad7ad42e85265a6b2f853b090401b633424"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "01c93808036c6baf86a18daa3605230bdd2dde0fa2b681d803dd9759cfeedde2"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f75d315f25c9fdb4b6d9dfe81073f4bbd8e474a"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "19e8ee0984fdbadbfdc425d7f60568d4608b91ca49860dd7bee7d72f68330509"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
git-tree-sha1 = "866ad5012316107ee3efd96d660cb1ed4eb22bf5"
os = "macos"

    [[Cgl.download]]
    sha256 = "ee112f631150099cbb9bd656945e91bc369d9c3dd7112cee495b3ef1ffd3348d"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.x86_64-apple-darwin.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0aa360e780d3d2c7365f82964883f65cb7d4e6d"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "56259801fe1ff9d268ecec792370987a2a85b36824e9ecc7fb918e48a937c31e"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.x86_64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79f12b426e0afd7409a21ba232971bdd56e9a761"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "37881760a4d63422ea3ee96eebb885e808b35d460a432a185e7f5b7d371f0193"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.x86_64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbc495d77687fe1d49e91e4d616deecab47fd5ba"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "2ca02b62f419695b2978c2996215d1c3d198cfeb97e393f5d0dfb41a124aad00"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.x86_64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8845dc0edf813408d18f1c332a35c3a7ccbde0a"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "8acc72da215bfae8b810c9bbcf7f9ead35f0b97b65b3c5adffdf844f693fe5c1"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.x86_64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7b28227f323fff3d6c9b3eccd116646519f3b5a"
os = "windows"

    [[Cgl.download]]
    sha256 = "9fa00e03ecffdf59a85b58ce9b08c7befca27f3843a21b4a2de8561683ea7910"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f48c07ed96a60f787109cd542dce39e41655b29"
os = "windows"

    [[Cgl.download]]
    sha256 = "258f7729faebbe7acdc63638bde06fec1d922fbe845270707873bd2e049816a1"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.200+0/Cgl.v0.6000.200.x86_64-w64-mingw32-cxx11.tar.gz"
