[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05f5e79800284ae44e3f78d0860a5e64d7b06533"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "c444e8b1e945140d1a3b43c47234b8a69cfd3cbf0a77b842e74acc2d9ba40e7f"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.aarch64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d0f217e83d247c8792a7cb28b17013b76c00308"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "daf6b7474b2df6e7fc7fd6c5e0c0c9d26dedc6da55b2c882de85223db5f8c353"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.aarch64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6736043df31b703df7b90cb9d26ae3054c067cc4"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "1d04a8c0ecac152a089d0dbfc8f071a422531d6cbbfbaf65ed304c6a6758d531"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96bdf280f3b6cbd1b92255414b5b3f1ba99e010d"
os = "windows"

    [[Cgl.download]]
    sha256 = "bafb7c77468627fe2fa12342833becf306d32df603c5a59b8dc8310286e28b60"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce2eadaf102daf08b44f199154fdef148ee8eed4"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "2b67a6ee172e72c0aac20bc3994f4d37e79a7394d89339ee45d87f0057095a13"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.i686-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2e669a5cc09042e0b8b6667751adbb47ba7bd26"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "73bc41767aacf746640973e988032850740b432d44704e505f63fccf22c6f4a1"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.x86_64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "798d6a87698ce52d8efedeb1645ca88a08862927"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "a74ed30d7363fa32d311befe0bdfc3fcf0b1d965d20c5758c3e7a86f1c958621"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20c2dd2772efea083ed6490a5fd0bbfeec699ef0"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "97fdb8090598cdcda6dd193ced6b6d1530040a4be89269bb730c4caf20fced3d"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.i686-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d01ab9e0933914a54849754ac85c208f99ee1bf"
os = "macos"

    [[Cgl.download]]
    sha256 = "b7c8da71876be0f983634c45b7c25a4c5d5bf80fac808e9004df598aeca0b0b8"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cde7f724db55631b42a2fc67fc07d3cb173dbdac"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "431c633dae09ef0877a066b175d66606a38ff22ba7e3f66e78af914f8cfff0e4"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.i686-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42d3c60887a238641143d9401a34eabf50c7de14"
os = "windows"

    [[Cgl.download]]
    sha256 = "c0ab409de6ee093d9f5665f39b5d2bc1ba2cd9cd349c48b54d4ad5b809fa41e3"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09f4e494ad5b95a040b65b67af6e8cee630bfcb9"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "a33cb719185f273636485cb7e7bbe5e8179db2f6885d5aa8bb2a9385a095cd71"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a8c73a80a38a5609153a8b218168f3b60e456e8"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "449c5c80d29ce7ace12bbef597d1bdc7f9a172a0c1c31f2be3e19fc86766ac6f"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b8deb169631f688a57ed1ddb8be7fb2cd62b67b"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "6373352c391587ee49ef497ced3c4cded02f6fcb75022c5bb07321da36d31d70"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.x86_64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6a73f487561535cab391a06f03213d18490ca84"
os = "macos"

    [[Cgl.download]]
    sha256 = "320ca0d97dfb0860626884bf84551b1c1aae91330ba12c8a4ca50c0039140ac9"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7122d9db5dfbf4a7a752a5db4d13c338e8b8585"
os = "windows"

    [[Cgl.download]]
    sha256 = "f1b28782f8b3b433f61d0517f4709b5a5d792250a5835dcc95a5de1f6a891438"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.i686-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d28b59162502d7d57557919348832f1ec0ff551"
os = "windows"

    [[Cgl.download]]
    sha256 = "903f956e36ed6751c596333d33abe40d0bc3ee74a6e3eb33b9073cbacb8aeb18"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.i686-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd25b67d6bc046561758a7b9d1599fee68379ae6"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "0024ea1c3bfff26d1850d4b4581c76f667325af196e68f0229a7c33b7183a155"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b27f21a84bd800459ea63218b7cc210ab7799d1c"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "a2c3229a4a7485cf6260b94aea56d3b4d887c6207c72a12c222a1e2ca6787f78"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21c8e1703f827c5e39b4ce2523607391cc9f177a"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "a428f1bc6e838e7c313a3a263ccc28c50d9ff5a0271f85511802a2a6bdd0f5ef"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0db96bb660114e5a3757f325a643d7972af7ae9f"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "fb8fa517178b9bcef4c822a2aaeb9b4fce3f724c426b939282569ee150f23a2a"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc553f85384a25a60304348115c2d92aa7ab6ec6"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "82673d2f455f9f319ed6b91c343b09525c507d1932663eacbc6f0ac4d67ae6d9"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+4/Cgl.v0.60.2.i686-linux-musl-cxx03.tar.gz"
