[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2374134a10decc4e4cdf1914f1859a9b248f7c34"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "8a7d67ce60facb9bd7f28e7ac75971acf9ab6deb2b036051ec38977458a380d2"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.aarch64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a133ba81af51fa86cfa6e53901d8b74098270a27"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "9da8250ca26b70fdd9c6fd91e0219a1e5ea0ef647db8cdb4d62390df568f48e9"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.aarch64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6033c1d0a4f347017ff78461c86880c6b9431560"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "73439a0cdbaaae43258a051afbf5c17df69877fc7516b6d53b759c31de94c640"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a449ad209fcf190466dd919f7ca1ec67379eb65f"
os = "windows"

    [[Cgl.download]]
    sha256 = "dbaa54592398b65fa95d34c88513fee2fdb6d2fbd03597ad584c8442fadfe600"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f1131d4262b4c00193931f9220a6d358f53ed0f"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "af22256b610abe4fed4243032351576c8da0a29c0f9de33f51d9cdab92e659ba"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.i686-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f9763db5f1ee39ef28c7bca43adf6ff3cba84bf"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "b8df19b59e237f8877fa7767fc713b502bfad029748be60f4ef771cf6453ae43"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.x86_64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a35bce50a75e95d13b863dc2af744fdb82c375d7"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "d5caed732e949c9bf5a4bc76b6b17446ab19ad6c094ab3b70c2d53572b1ded2b"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd94d8d3c792e1582e1fffbbf6ca295fff2cfe2a"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "fe60714e9276ead00baad2828e03a21d1887088c8a759455dcf148ecf4706434"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.i686-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f30bb0aa76846832145d7fdba093a331cd6d107"
os = "macos"

    [[Cgl.download]]
    sha256 = "5fc90cff321fcffe7f6d367603d969710b575ddc3e1eeccf43ea2fd2ba519841"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "405f003e3e828682b5af5d37b32e87588548a21f"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "b4b09c26176d9b451ad05561e7844dd2feb067eea5f07f872863f5a18afbec8d"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.i686-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f3a7e70122b5f3652bbacafd2f1210e212b0bf6"
os = "windows"

    [[Cgl.download]]
    sha256 = "a575d6d4a5722fadafded63d23dd963a5591292a86f492cb7a2ac253b9d340de"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1ee9217f505ba3b9c37a7978ffe55aceaa2c92b"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "617b6c67492d55aa1e6bbf964d9a094eb1f1983729416aac7a10d760eeb16216"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cd7dfb59edd80f83944865a1c67bf9429e70ddd"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "047d66653b3e019328edf38349169610358763205a754b65957f55032e608528"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd0e66887e50e6b4fb6570c81bba62246cb08eb2"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "f14bdd750488b4e8482c1e6713dbf696928ff9adca2d73664367e8a24d34d149"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.x86_64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebe3220cbc80fb3846a69b67f053ff42e5282d7e"
os = "macos"

    [[Cgl.download]]
    sha256 = "42bff07a91294237a70d7ae01895ff4c1bcf0a58072d0bb2427b4e545966b802"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97b35f9fa8ec1c6d4221b94cfe78c0b9f2ac611c"
os = "windows"

    [[Cgl.download]]
    sha256 = "b55e2911c167669ca93a8f40b87cd4272e1a89d5d0e895f3dd4260c9454874f5"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.i686-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89285eb13df6ae35a7cc9350b1c46027cc543f2d"
os = "windows"

    [[Cgl.download]]
    sha256 = "439e8cd87ed7a0aadb8d0b90b123c81d321992deee7fbc7afddd4b83dc5a7942"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.i686-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1b8daea95f0bdbe0455f022f92bcffa3c547044"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "7431b2671d986f3fd1ea77c422ee38725389b593b5d543d14dce4301635ded55"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d33fea1180a5c25c6945f6b71cf8e470df677cba"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "9b9a3e59187e9484ab16d7a712f3b9298b2c986974e340269c7601031f3cdf98"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3475472fe788f9d85d159772a16cab5b05a67b5"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "00bb6d4556a14f83487eb2119c48967243c7acc0fb111653b23147d735677af5"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c27ad3b844a1a4bef3ea5874fe24c2ea114581a"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "fadd5f4095a8fc4f338b2b45b7bd7648874b4d88a452d4d282cc3092c317f296"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "433f2ad6e1768cad5a5f0bc93d9b762b1fb3d172"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "ceaa626a6b5a3144062a5da86160d3b3d03ccece05c9d372aec0d76c02645640"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+3/Cgl.v0.60.2.i686-linux-musl-cxx03.tar.gz"
