[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b913921063993b9a3ff4a26d334bb0904110943"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "8e90cbf3c2c566f12081c6bedf3f70111eb6b2e88f834014c9f40bc6e0471734"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.aarch64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "734bb45389b6a9fdd70ba8fd58c0fa046d3acd82"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "294a4185f31c223064831a2ec62537e945f1dd69f9ed33b406555ca34d03650e"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.aarch64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "149fe1eff40cce27702b4bfaebec4d79e9432f02"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "676edd3ec54add672405efbd9cf6e74fafc47475235761480132686eaab3df4e"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9311510534b58766301811837228fd533565cac"
os = "windows"

    [[Cgl.download]]
    sha256 = "9fbf81e359e47732a717adf5411929da75b7dc1b3cafd1aa6e653ab8f75157e3"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e2aded158ba5c82fb3745657d9b6ccb4feee0f9"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "06267ffa17f8c49161defb6da242b02cb2639b6cec5b26dfa8113d256f56a266"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.i686-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22b8ef1df7c63289fef361f0d13e3f87a40afdef"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "1ce9f9e59ef3fab29c599a2b41ed5195f9a9e71ce61aedab1bde4b70ab27aaa6"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.x86_64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "482d490a1a67b2d19d750061b179a666c4b92293"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "ce4fbea1a149ed9593a39feeeea818480bbd30fd0aa0e0ffd76789b857168600"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d494c6da81889c426ba0f0fbf42478cd362e5a51"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "46a5c86318d6c937364b9a1d76f4c010bc4b2b5771c386d60b2d3187aa7a7fc5"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.i686-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd02609e86a318adc78efa10bfad461017ac0d64"
os = "macos"

    [[Cgl.download]]
    sha256 = "8ecd471a01aa2cbc8771ed948574eb7adbad201817a010340446866bf8b80249"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05fa9a8ca1bdbe729d07e215a05115c4d0a13b68"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "ae530e0396d328e4648bdab4d93f500e9e28ea539e2c4b242ca00a81b6130d80"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.i686-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e222215a41f76455f40afd0aa830184dbb7e5040"
os = "windows"

    [[Cgl.download]]
    sha256 = "1ee259d30c572463da168179e92f348b3f3941f152f6f634c33612c6ad4a8ee1"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8431256120931e7dbcbdcaa4e4a76ddc577dfb26"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "d17a73982a03152e669cf924d53ec7ce7832c716f94955881540c478a7bc2394"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4034984ab2fd4c0a203d0efbd457ebc2fc52284d"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "cfde0f02db831e380df359fb63914563796903c03d9652776752d6eaae32d873"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a8eb7847be89c55170f276d1c647de74ff6c8b0"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "6bea661d378bcb5240205ef39e59333341289cde8c459cc3b8105dd145bb854a"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.x86_64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0dd80f586336871ba569b19d75e22a495da90a8c"
os = "macos"

    [[Cgl.download]]
    sha256 = "c3a755d3215eabe83d1837c03575a23eeaa9ba2ba4e99a04860b8206e623b6df"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22d6621b530ecf63ac3614129e446b9e882ffd69"
os = "windows"

    [[Cgl.download]]
    sha256 = "fdda6dfba2dd20d6e7be20ebfc61637e1e2c26d77f5032d953da0ac9e4b33dd2"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.i686-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aecb2cbc38e07efbadb8dba17042910dbecc1d07"
os = "windows"

    [[Cgl.download]]
    sha256 = "0c111c3dd99da953c8505fb369ff83f68cea367f3ac238490c64fff6df368649"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.i686-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3dcca51b34e5215428fc98e5e76055e3da935ffa"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "6ba7938bec0e06569417b3ff6f5972658f122c4866886880477ef329193493d9"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4826cf01161f25c41cda8cb58548c4eba2570896"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "63a142ccdff3445dfa5e6cbee055be94d699aeee92a2331cfde54c02810e1317"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6d9065a66ad123711aa464347be0e6cf47d4459"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "b607842a369bad20df565af106b851d9ea37a710105090b4576b128d313147e8"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0117281f4eae71eab43a1a8cb94c892330c2d0d8"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "b83864b02c08b6f5d5ee4ada8f6704533ee6c2d7fc1785d9d953550eeb414558"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbffec7ff3946b5eb8a275ee27ace9e2646aa9e6"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "f526bd08dcb3f4656e5dd4e389c7a1cd34b15f9b7758d2f786586a94ab7cfec9"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.60.2+0/Cgl.v0.60.2.i686-linux-musl-cxx03.tar.gz"
