# Autogenerated wrapper script for Cgl_jll for x86_64-apple-darwin
export libCgl

using Clp_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Cgl")
JLLWrappers.@declare_library_product(libCgl, "@rpath/libCgl.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Clp_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libCgl,
        "lib/libCgl.1.10.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
